# -*- coding: utf-8 -*-
"""ventasComercioMatafuegos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_n8vgYB04fV4nX2aJjVd4cd7_juO19Z5
"""

#|---------------------------|
#| Instalación de Librerias -|
#|---------------------------|

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#|---------------------------|
#| Carga de Datos           -|
#|---------------------------|

url = "https://raw.githubusercontent.com/SilvinaMoreno/ventasComercioMatafuegos/refs/heads/main/01.datos/ventas_matafuegos_2025.csv"

df = pd.read_csv(url)
df.head()

#|------------------------------|
#| Limpieza de Datos           -|
#|------------------------------|

print ("TIPOS DE DATOS\n")
df.info()

df['date'] = pd.to_datetime(df['date'])

print ("\nDatos DUPLICADOS\n")
df.duplicated().sum()

print ("\nDescripción\n")
df.describe()

#|-------------------|
#| Analisis         -|
#|-------------------|

# Primero, seccionamos los datos para poder racionalizar la información de manera prolija

df['Fecha'] = df['date'].dt.date
df['Hora'] = df['date'].dt.hour
df['Día'] = df['date'].dt.day_name()
df['Mes'] = df['date'].dt.month_name()
df['Semana'] = df['date'].dt.isocalendar().week
df['Trimestre'] = df['date'].dt.quarter

#df.head()